Add shared GHA for ruby
theforeman/hammer-cli-foreman-kubevirt pull request #26
Opened 2024-03-13 09:22 UTC by girijaasoni

2024-03-14 09:03 UTC, girijaasoni commented on Gemfile
> +  gem 'rubocop', '~> 1.57.0'
Thanks Leos, updated!

2024-03-14 10:06 UTC, nofaralfasi commented on hammer_cli_foreman_kubevirt.gemspec
>    s.add_dependency 'hammer_cli_foreman', '>=0.17.0'
```suggestion
  s.add_dependency 'hammer_cli_foreman', '~> 3.10'
```

2024-03-14 10:10 UTC, nofaralfasi commented on .rubocop.yml
> -inherit_from:
If you drop this, then you should also delete `.rubocop_todo.yml`

2024-03-14 10:17 UTC, nofaralfasi commented on hammer_cli_foreman_kubevirt.gemspec
> -  s.add_development_dependency 'rdoc'
Do you know what this gem is used for? I noticed there's a related task in the `Rakefile`.

2024-03-14 10:35 UTC, nofaralfasi commented on Gemfile
> +  gem 'rubocop', '~> 1.57.0'
I only see this gem required in `smary_proxy_*` plugins.

2024-03-14 10:37 UTC, girijaasoni commented on hammer_cli_foreman_kubevirt.gemspec
> -  s.add_development_dependency 'rdoc'
I'm not sure what it's used for but I did not remove it, I have added the development dependency in the gemfile

2024-03-14 10:39 UTC, nofaralfasi commented on hammer_cli_foreman_kubevirt.gemspec
> -  s.add_development_dependency 'rdoc'
Where? I don't see it.

2024-03-14 10:42 UTC, girijaasoni commented on hammer_cli_foreman_kubevirt.gemspec
> -  s.add_development_dependency 'rdoc'
[here](https://github.com/theforeman/hammer-cli-foreman-kubevirt/pull/26/commits/5e817e8db9a73095766478abad7f3c8b7557c660#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR8)

2024-03-14 10:46 UTC, girijaasoni commented on hammer_cli_foreman_kubevirt.gemspec
> -  s.add_development_dependency 'rdoc'
Thanks , Updated rdoc in the gemfile, I thought you meant gettext.

2024-03-17 12:42 UTC, nofaralfasi approved these changes

2024-03-17 12:50 UTC, nofaralfasi requested changes
Please also update the Rakefile.

2024-03-18 12:57 UTC, merged